WH40KKT/WH40KKT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ktGuide/', include('ktGuide.urls'))
]

WH40KKT/ktGuide/urls.py
from django.urls import path
from . import views

app_name = 'ktGuide'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login_page/', views.login_page, name='login_page'),
    path('logout_page/', views.logout_page, name='logout_page'),
    path('register/', views.register, name='register'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('makeGuide/', views.make_guide, name='make_guide'),
    path('view_guide/<int:guide_id>/', views.view_guide, name='view_guide'),
    path('get_units/', views.get_units, name='get_units'),
    path('get_unit_stuff/', views.get_unit_stuff, name='get_unit_stuff'),
    path('get_presentable/', views.get_presentable, name='get_presentable'),
    path('submit_guide/', views.submit_guide, name='submit_guide'),
    path('submit_comment/', views.submit_comment, name='submit_comment')
]

WH40KKT/ktGuide/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class Army(models.Model):
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class Ability(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.name

class Specialist(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Weapon(models.Model):
    army = models.ForeignKey(Army, on_delete=models.PROTECT) 
    name = models.CharField(max_length=50)
    weapon_range = models.CharField(max_length=50)
    weapon_type = models.CharField(max_length=50)
    s = models.CharField(max_length=50)
    ap = models.CharField(max_length=50)
    d = models.CharField(max_length=50)
    abilities = models.CharField(max_length=1000)
    pts = models.IntegerField()

    def __str__(self):
        return self.name

class Unit(models.Model):
    army = models.ForeignKey(Army, on_delete=models.PROTECT)
    name = models.CharField(max_length=50)
    m = models.IntegerField()
    ws = models.IntegerField()
    bs = models.IntegerField()
    s = models.IntegerField()
    t = models.IntegerField()
    w = models.IntegerField()
    a = models.IntegerField()
    ld = models.IntegerField()
    sv = models.IntegerField()
    max_units = models.CharField(max_length=50)
    weapons_list = models.ManyToManyField(Weapon, related_name='weapon')
    ability_list = models.ManyToManyField(Ability, related_name='ability')
    specialist_list = models.ManyToManyField(Specialist, related_name='specialist')
    point_value = models.IntegerField()

    def __str__(self):
        return self.name

class User(AbstractUser):
    username = models.CharField(max_length=26, unique=True)
    email = models.EmailField(
        verbose_name='email address',
        max_length=100,
        unique=True
    )
    admin = models.BooleanField(default=False)
    bio = models.CharField(max_length=800, default="Bio goes here")

    @property
    def is_admin(self):
        return self.admin

class Guide(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    army = models.ForeignKey(Army, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default="Title")
    guide_desc = models.CharField(max_length=10000, default="stuff goes here")
    point_value = models.IntegerField(default=0)
    votes = models.IntegerField(default=0)
    date_created = models.DateTimeField()

class GuideUnit(models.Model):
    name = models.CharField(max_length=50)
    guide = models.ForeignKey(Guide, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.PROTECT)
    weapon = models.ForeignKey(Weapon, on_delete=models.PROTECT)
    role = models.ForeignKey(Specialist, on_delete=models.PROTECT)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    guide = models.ForeignKey(Guide, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    date_created = models.DateTimeField()

WH40KKT/ktGuide/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User
from django.core.exceptions import ValidationError

class CustomUserForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=5, max_length=26)
    email = forms.EmailField(label='Enter Email')
    password_enter = forms.CharField(label='Enter Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    def clean(self):
        cd = self.cleaned_data
        
        check_username = User.objects.filter(username=cd.get('username'))
        if check_username.count() > 0:
            self.add_error('email', 'This username already exists!')

        check_email = User.objects.filter(email=cd.get('email'))
        if check_email.count() > 0:
            self.add_error('email', 'This email already exists!')

        if cd.get('password_enter') != cd.get('password_confirm'):
            self.add_error('password_confirm', 'passwords do not match!')
        return cd
        

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password_confirm']
        )

WH40KKT/ktGuide/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import CustomUserForm
from .models import Army, Unit, Weapon, Specialist, Guide, GuideUnit, Comment
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.template import loader
import datetime
import json

def index(request):
    page = request.GET.get('page',1)
    template = loader.get_template('ktGuide/index.html')
    if Guide.objects.count():
        list_of_guides = Guide.objects.order_by('title')
        paginator = Paginator(list_of_guides, 20)
        context = {
            'list_of_guides': list_of_guides
        }
        return HttpResponse(template.render(context, request))
    else:
        context = {
            'message': 'There are no guides to view!'
        }
        return HttpResponse(template.render(context, request))
    

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            print("logging in...")
            return HttpResponseRedirect(reverse('ktGuide:index'))
        else:
            return render(request, 'ktGuide/login_page.html', {'message':'Username or Password is incorrect'})
    context = {}
    template = loader.get_template('ktGuide/login_page.html')
    return HttpResponse(template.render(context, request))

def logout_page(request):
    logout(request)
    print('logging out...')
    return HttpResponseRedirect(reverse('ktGuide:login_page'))

def register(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            context = {'message':'Account created!'}
            template = loader.get_template('ktGuide/login_page.html')
            return HttpResponse(template.render(context, request))
    else:
        form = CustomUserForm()
    context = {'form':form}
    return render(request, 'ktGuide/register.html', context)

@login_required
def myprofile(request):
    context = {}
    return render(request, 'ktGuide/myprofile.html', context)

@login_required
def make_guide(request):
    context = {
        'army_list': Army.objects.order_by('name')
    }
    return render(request, 'ktGuide/makeguide.html', context)

@login_required
def get_units(request):
    army_id = request.GET['army_id']
    army = Army.objects.get(id=army_id)

    units = Unit.objects.filter(army_id=army_id)
    units = units.order_by('name')
    units_json = []
    for unit in units:
        units_json.append({
            'id': unit.id,
            'name': unit.name,
        })
        print(units_json)
    return JsonResponse({'army': army.id, 'units': units_json})

@login_required
def get_unit_stuff(request):
    unit_id = request.GET['unit_id']
    unit = Unit.objects.get(id=unit_id)

    weapons = unit.weapons_list.order_by('name')
    specialists = unit.specialist_list.order_by('name')

    weapons_json = []
    specialists_json = []

    for weapon in weapons:
        weapons_json.append({
            'id': weapon.id,
            'name': weapon.name
        })

    for specialist in specialists:
        specialists_json.append({
            'id': specialist.id,
            'name': specialist.name
        })

    return JsonResponse({'unit': unit.id, 'weapons': weapons_json, 'specialists': specialists_json})

@login_required
def get_presentable(request):
    unit_name = request.GET['unit_name']
    unit_id = request.GET['unit_id']
    unit_weapon_id = request.GET['unit_weapon_id']
    unit_specialist_id = request.GET['unit_specialist_id']

    unit = Unit.objects.get(id=unit_id).name
    weapon = Weapon.objects.get(id=unit_weapon_id).name
    specialist = Specialist.objects.get(id=unit_specialist_id).name

    return JsonResponse({'name': unit_name, 'unit': unit, 'weapon': weapon, 'specialist':specialist})

@login_required
def submit_guide(request):
    data = json.loads(request.body)
    date = datetime.datetime.now()

    army_id = data['army']
    title = data['title']
    text = data['text']

    pts = 0

    for unit in data['units']:
        uni_pts = Unit.objects.get(id=int(unit['unit']))
        wep_pts = Weapon.objects.get(id=int(unit['weapon']))
        pts += uni_pts.point_value + wep_pts.pts

    guide = Guide(author=request.user, army=Army.objects.get(id=army_id), title=title, guide_desc=text, point_value=pts, date_created=date)
    guide.save()

    for unit in data['units']:
        guide_unit = GuideUnit(name=unit['name'], guide=guide, unit=Unit.objects.get(id=int(unit['unit'])), weapon=Weapon.objects.get(id=int(unit['weapon'])), role=Specialist.objects.get(id=int(unit['specialist'])))
        guide_unit.save()

    return HttpResponse(guide.id)

@login_required
def submit_comment(request):
    data = json.loads(request.body)
    author = request.user
    date = datetime.datetime.now()
    comment_text = data['comment']
    guide = Guide.objects.get(id=data['id'])
    
    comment = Comment(author=author, guide=guide, content=comment_text, date_created=date)
    comment.save()

    return HttpResponse(guide.id)


def view_guide(request, guide_id):
    guide = ''
    try:
        guide = Guide.objects.get(id=guide_id)
    except Guide.DoesNotExist:
        template = loader.get_template('ktGuide/404.html')
        return HttpResponse(template.render({}, request))

    list_of_comments = Comment.objects.filter(guide=guide_id)
    list_of_units = GuideUnit.objects.filter(guide=guide_id)
    list_of_comments = list_of_comments.order_by('date_created')
    list_of_units = list_of_units.order_by('name')
    template = loader.get_template('ktGuide/viewguide.html')
    context = {
        'guide': guide,
        'list_of_comments': list_of_comments,
        'list_of_units': list_of_units,
    }
    return HttpResponse(template.render(context, request))

WH40KKT/ktGuide/templates/ktGuide/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ktGuide/style.css' %}">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="/ktGuide/index" id="logo">
            {% load static %}
            <img  src="{% static 'ktGuide/KTG.png' %}">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/ktGuide/index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ktGuide/makeGuide">Make Guide</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My Stuff
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/ktGuide/myprofile">My Profile</a>
                        <a class="dropdown-item" href="#">My Guide</a>
                    </div>
                </li>
                <li>
                    <a class="nav-link" href="/ktGuide/login_page">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="/ktGuide/register">Register</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <div>
                <a>Logged in as {{request.user}}</a>
                <a class="btn btn-outline-danger" href="/ktGuide/logout_page">Logout</a>
            </div>
            {% endif %}
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Guides" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        
    </nav>
    {% if list_of_guides %}
    <div id="guide_content">
        {% for guide in list_of_guides %}
        <div class="media bg-dark text-white" id="guide">
            <a class="pull-left" href="#">
                {% if guide.army.name == 'Necrons' %}
                {% load static %}
                <img src="{% static 'ktGuide/necronImage.png' %}" alt="Necron Icon">
                {% elif guide.army.name == 'Harlequins' %}
                {% load static %}
                <img src="{% static 'ktGuide/harlequinImage.png' %}" alt="Harlequin Icon">
                {% endif %}
            </a>
            <div id="vote_system">
                {% load static %}
                <img id="arrow" src="{% static 'ktGuide/arrowUp.png' %}" alt="ArrowUp">
                <a>{{guide.votes}}</a>
                {% load static %}
                <img id="arrow" src="{% static 'ktGuide/arrowDown.png' %}" alt="ArrowDown">
            </div>
            <div class="media-body">
                <div>
                    <a href="/ktGuide/view_guide/{{ guide.id }}" class="title">{{ guide.title }}</a>
                </div>
                <a class="points_author">{{ guide.point_value }} points | Author: {{ guide.author.username }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <a>{{ message }}</a>
    {% endif %}
</body>
</html>

WH40KKT/ktGuide/templates/ktGuide/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ktGuide/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="/ktGuide/index" id="logo">
            {% load static %}
            <img  src="{% static 'ktGuide/KTG.png' %}">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/ktGuide/index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Make Guide</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My Stuff
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/ktGuide/myprofile">My Profile</a>
                        <a class="dropdown-item" href="#">My Guide</a>
                    </div>
                </li>
                <li>
                    <a class="nav-link active" href="/ktGuide/login">Login <span class="sr-only">(current)</span></a>
                </li>
                <li>
                    <a class="nav-link" href="/ktGuide/register">Register</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Guides" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
    </nav>
    <a>Log In</a>
    <form action="{% url 'ktGuide:login_user' %}" method="POST">
        {% csrf_token %}
        <div>
            <div>
                <label>Username:</label>
                <input type="text" placeholder="Username">
            </div>
            <div>
                <label>Password:</label>
                <input type="password"  placeholder="Password">
            </div>
        </div>
    </form>
</body>
</html>

WH40KKT/ktGuide/templates/ktGuide/makeguide.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ktGuide/style.css' %}">
    {% load static %}
    <link rel="shortcut icon" type="img" href="{% static 'ktGuide/skull_favicon.png' %}">
    <title>Make Guide</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="/ktGuide/index" id="logo">
            {% load static %}
            <img  src="{% static 'ktGuide/KTG.png' %}">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/ktGuide/index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/ktGuide/makeGuide">Make Guide<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My Stuff
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/ktGuide/myprofile">My Profile</a>
                        <a class="dropdown-item" href="#">My Guide</a>
                    </div>
                </li>
                <li>
                    <a class="nav-link" href="/ktGuide/login_page">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="/ktGuide/register">Register</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <div>
                <a>Logged in as {{request.user}}</a>
                <a class="btn btn-danger" href="/ktGuide/logout_page">Logout</a>
            </div>
            {% endif %}
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Guides" aria-label="Search">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
          </div>
    </nav>
    <div id="app">
        <h2>Army & Title</h2>
        <div id="guide_army">
            <label>Army:</label>
            <select v-model="selected_army_id" v-on:change="getUnits" :disabled="selected_army_id != ''">
                <option value="">Select an Army</option>
                {% for army in army_list %}
                <option value="{{ army.id }}">{{ army.name }}</option>
                {% endfor %}
            </select>
            <label>Title:</label>
            <input type="text" v-model="guide_title">
        </div>
        <h2>Units</h2>
        <div id="guide_unit_add">
            <label>Name: </label>
            <input type="text" v-model="selected_unit_name">
            <label>Unit: </label>
            <select v-model="selected_unit_id" v-on:change="getUnitStuff">
                <option value="">Select a unit</option>
                <option v-for="unit in display_units" v-bind:value="unit.id">[[ unit.name ]]</option>
            </select>
            <label>Weapon: </label>
            <select v-model="selected_weapon_id">
                <option value="">Select a Weapon</option>
                <option v-for="weapon in weapons" v-bind:value="weapon.id">[[ weapon.name ]]</option>
            </select>
            <label>Specialist: </label>
            <select v-model="selected_specialist_id">
                <option value="">Select a Specialist</option>
                <option v-for="specialist in specialists" v-bind:value="specialist.id">[[ specialist.name ]]</option>
            </select>
            <button v-on:click="addUnit" class="btn btn-success">Add Unit</button>
        </div>
        <p v-if="message">[[message]]</p>
        <div class="table-responseive">
            <table>
                <tr>
                    <th scope="row" class="section-odd">Name</th>
                    <td class="section-even">Unit Type</td>
                    <td class="section-odd">Weapon</td>
                    <td class="section-even">Specialist</td>
                </tr>
                <tr v-for="(unit, index) in guide_presentable">
                    <th scope="row" class="section-odd">[[unit.name]]</th>
                    <td class="section-even">[[unit.unit]]</td>
                    <td class="section-odd">[[unit.weapon]]</td>
                    <td class="section-even">[[unit.specialist]]</td>
                    <td><button v-on:click="removeUnit(index)" class="btn btn-danger">Remove Unit</button></td>
                </tr>
            </table>
        </div>
        <h2>Strategy</h2>
        <textarea v-model="guide_bio"></textarea>
        <button v-on:click="submitGuide">Submit</button>
    </div>
    <script>
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFTOKEN'
        let app = new Vue({
            el: '#app',
            delimiters: ['[[',']]'],
            data: {
                selected_army_id: '',
                selected_unit_id: '',
                selected_weapon_id: '',
                selected_specialist_id: '',
                selected_unit_name: '',
                guide_bio: '',
                guide_title: '',
                message: '',
                display_units: [],
                weapons: [],
                specialists: [],
                guide_units: [],
                guide_presentable: []
            },
            methods: {
                getUnits: function() {
                    axios({
                        method: 'get',
                        url: '{% url "ktGuide:get_units" %}',
                        params: {
                            army_id: this.selected_army_id
                        }
                    }).then(response => {
                        this.selected_unit_id = '',
                        this.display_units = response.data.units
                    })
                },
                getUnitStuff: function() {
                    axios({
                        method: 'get',
                        url: '{% url "ktGuide:get_unit_stuff" %}',
                        params:{
                            unit_id: this.selected_unit_id
                        }
                    }).then(response => {
                        this.selected_specialist_id = '',
                        this.specialists = response.data.specialists,
                        this.selected_weapon_id = '',
                        this.weapons = response.data.weapons
                    })
                },
                addUnit: function() {
                    if(this.selected_unit_name.length > 50){
                        this.message = 'The units name is too long! (Max 50 characters)'
                    }else if(this.selected_unit_name && this.selected_unit_id && this.selected_weapon_id && this.selected_specialist_id){
                        this.guide_units.push({'name': this.selected_unit_name, 'unit': this.selected_unit_id, 'weapon': this.selected_weapon_id, 'specialist': this.selected_specialist_id})
                        this.message = ''
                        axios({
                            method: 'get',
                            url: '{% url "ktGuide:get_presentable" %}',
                            params:{
                                unit_name: this.selected_unit_name,
                                unit_id: this.selected_unit_id,
                                unit_weapon_id: this.selected_weapon_id,
                                unit_specialist_id: this.selected_specialist_id
                            }
                        }).then(response => {
                            this.guide_presentable.push({'name': response.data.name, 'unit': response.data.unit, 'weapon': response.data.weapon, 'specialist': response.data.specialist})
                        })
                    }else{
                        this.message = 'Please enter unit data into all fields!'
                    }
                },
                removeUnit: function(index) {
                    this.guide_units.splice(index, 1)
                    this.guide_presentable.splice(index, 1)
                },
                submitGuide: function() {
                    if(this.guide_bio.length > 10000)
                    {
                        this.message = 'The guide length is too long! (Max 10000 Characters!)'
                    }
                    else{
                        this.message = ''
                        axios({
                            method: 'post',
                            url: '{% url "ktGuide:submit_guide" %}',
                            data: {
                                army: this.selected_army_id,
                                title: this.guide_title,
                                units: this.guide_units,
                                text: this.guide_bio
                            },
                        }).then(response => {
                            this.selected_army_id= '',
                            this.selected_unit_id= '',
                            this.selected_weapon_id= '',
                            this.selected_specialist_id= '',
                            this.selected_unit_name= '',
                            this.guide_bio= '',
                            this.guide_title= '',
                            this.message= '',
                            this.display_units= [],
                            this.weapons= [],
                            this.specialists= [],
                            this.guide_units= [],
                            this.guide_presentable= []
                            window.location = "/ktGuide/view_guide/" + response.data
                        })
                    }
                }
            }
        })
    </script>
</body>
</html>